### ISSUE TITLE
error    import pkg_resources

### ISSUE THREAD

**Issue by ainteligencia** [arturomedcass/live_voice_activity_detection#1]
vity_detection# python3 simple_vad.py 
Traceback (most recent call last):
  File "/home/dmolina/Documentos/pruebas/Prueba/live_voice_activity_detection/simple_vad.py", line 1, in <module>
    import webrtcvad
  File "/home/dmolina/Documentos/pruebas/Prueba/live_voice_activity_detection/venv-prueba/lib/python3.12/site-packages/webrtcvad.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(venv-prueba) root@thoth:/home/dmolina/Documentos/pruebas/Prueba/live_voice_activity_detection#

**Comment by arturomedcass** [comment]
This seems to be a problem with your package installations, not with the code. Please check that you have installed the webrtcvad package correctly in [its repository](https://github.com/wiseman/py-webrtcvad)
